# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:eess.*' 

# 検索キーワード
keywords:
        driver state detect: 5
        mind wandering: 3
        cognitive distraction: 3
        anormal: 2
        fatigue: 1
        drowsiness: 1
        readiness: 1

# 通知の閾値
score_threshold: 5
